dist: trusty
sudo: false
language: bash
python:
  - "3.6"
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
install: ci/install.sh
script: ci/all.sh
cache:
  bundler: true
  pip: true
  yarn: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  fast_finish: true
