dist: trusty
sudo: false
language: python
python:
  - "3.6"
install: ci/install.sh
script: ci/all.sh
cache:
  bundler: true
  pip: true
  yarn: true
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
