"we don't want to be compatible with vi.
set nocompatible

function! EnsureDirExists (dirarg)
    let l:dir=expand(a:dirarg)
    if !isdirectory(l:dir)
        call mkdir(l:dir,'p')
    endif
endfunction

" Enable syntax highlighting
syntax on
" I'm usually on a light background
colorscheme zellner
set bg=light

" One of the most important options to activate. Allows you to switch from an
" unsaved buffer without saving it first. Also allows you to keep an undo
" history for multiple files. Vim will complain if you try to quit without
" saving, and swap files will keep you safe if your computer crashes.
set hidden

" Vim Files 
set backupdir=~/.vim/backup
call EnsureDirExists(&backupdir)
" Prevent backups from overwriting each other. The naming is weird,
" since I'm using the 'backupext' variable to append the path.
" So the file '/home/docwhat/.vimrc' becomes '.vimrc%home%docwhat~'
au BufWritePre * let &backupext = substitute(expand('%:p:h'), '/', '%', 'g') . '~'

" for swap file
set directory+=~/.vim/swap// " double / so that the complete path gets used
set directory+=.
call EnsureDirExists("~/.vim/swap")


" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

"set clipboard=unnamed,unnamedplus,autoselect
set clipboard=

" Highlight searches (use <C-L> to temporarily turn off highlighting; see the
" mapping of <C-L> below)
set hlsearch
" But remove the highlighting when i type ctrl-l
:nnoremap <silent> <C-l> :nohl<CR><C-l>

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" When opening a new line and no filetype-specific indenting is enabled, keep
" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" Stop certain movements from always going to the first character of a line.
" While this behaviour deviates from that of Vi, it does what most users
" coming from other editors would expect.
set nostartofline

" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler

" Always display the status line, even if only one window is displayed
set laststatus=2

" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

" use ctags instead of cscope for :tags
set nocst

if has('mouse')
	" Enable use of the mouse for all modes
	"set mouse=a
endif

" Set the command window height to 2 lines, to avoid many cases of having to
" "press <Enter> to continue"
set cmdheight=2

" Display line numbers on the left
set number

" Quickly time out on keycodes, but never time out on mappings
set notimeout ttimeout ttimeoutlen=200

"show lines above and below current position at all times
set scrolloff=2

" Tabbing Options 
"
" Taken from joe @ sw
set smarttab
set smartindent
set showmatch		" Show matching brackets.

set incsearch		" Incremental search

set autowrite		" Automatically save before commands like :next and :make

set noerrorbells
set novisualbell

set showtabline=2
set tabpagemax=1000

" Automatically cd into the directory that the file is in
set autochdir

if has("persistent_undo")
	set undodir=~/.vim/undo
	set undofile
	set undoreload=10000	"maximum number lines to save for undo on a buffer reload
    call EnsureDirExists(&undodir)
endif
set undolevels=1000		"maximum number of changes that can be undone
" }}}
" Indentation options 
"

" Toggle between 'paste' and 'nopaste'
set pastetoggle=<F12>
set pastetoggle=<F8>

" }}}
" Mappings 
"

" Map Y to act like D and C, i.e. to yank until EOL, rather than act as yy,
" which is the default
map Y y$

" Map <C-L> (redraw screen) to also turn off search highlighting until the
" next search
nnoremap <C-L> :nohl<CR><C-L>

" If using a git repo, correctly set the tags directory.
au BufRead,BufNewFile * let project_dir = system("cd ".shellescape(expand("%:p:h"))." && git rev-parse --show-toplevel")
au BufRead,BufNewFile * let &tags = project_dir[:-2]."/.git/tags,./.tags"

let mapleader = ","

"Little trick to find ending whitespace in docs
if version >= 703
	set listchars=tab:>-,trail:*,eol:$,conceal:#,nbsp:_,extends:!,precedes:!
endif
"hi nontext ctermfg=red

"Taken from joe @ sw
nmap <silent> <C-j> <Esc>:exe "silent! tabm " . (tabpagenr() - 2)<CR>
nmap <silent> <C-k> <Esc>:exe "silent! tabm " . tabpagenr()<CR>
nmap <silent> <C-f> <Esc>:exe "FufFile"<CR>
nmap <silent> <F9> <Esc>:call ToggleLineTooLong()<CR>

"Taken from ryan
"Q -- :noh (clear highlighting)
map Q :noh<RETURN>
"S -- split line at char under cursor
map S i<RETURN><ESC>==k$


"}}}

"Auto Commands

	" Remove any trailing whitespace that is in the file
"	autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif
"	call histdel("search", -1)
"

if &term == "xterm" || &term == "xterm-color"
	set grepprg=grep\ -nH\ $*
	
endif

" Cool tab completion stuff
set wildmode=list:longest,full

" highlight trailing whitespace and tabs after spaces in leading whitespace
"highlight ExtraWhitespace ctermbg=red guibg=red
"autocmd BufWinEnter *.c match ExtraWhitespace /^\s*     \|\s\+$/
"autocmd InsertEnter *.c match ExtraWhitespace /^\s*     \|\s\+\%#\@<!$/
"autocmd InsertLeave *.c match ExtraWhitespace /^\s*     \|\s\+$/
"autocmd BufWinLeave *.c call clearmatches()


set foldenable
set foldmethod=marker

au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

"  function that highlights lines longer than 80 characters
let g:hl_visible = 1
function! ToggleLineTooLong()
    if g:hl_visible == 1
        match
        let g:hl_visible = 0
    else
        hi LineTooLong cterm=bold ctermbg=red guibg=LightYellow
        exe 'match LineTooLong /\%>' . &textwidth . 'v.\+/'
        let g:hl_visible = 1
    endif
endfunction
" }}}

" Set defaults
set tabstop=8
set shiftwidth=8

" Includes 
source ~/.conf/vim/language.vim
source ~/.conf/vim/statusline.vim
source ~/.conf/vim/plugins.vim

"try this:
"set tildeop

set completeopt=menuone

set cm=blowfish

command W w
command WQ wq
command Wq wq
command Q q


" now set it up to change the status line based on mode
if version >= 700
	au InsertEnter * hi StatusLine term=reverse ctermbg=5 gui=undercurl guisp=Magenta
	au InsertLeave * hi StatusLine term=reverse ctermfg=0 ctermbg=2 gui=bold,reverse
endif

" Determine the type of a file based on its name and its contents.
if has("autocmd")
    filetype indent on
    filetype plugin on
endif

set modeline
set modelines=2

if filereadable(glob("~/.vimrc.local"))
	source ~/.vimrc.local
endif
