"we don't want to be compatible with vi.
set nocompatible
"{{{Auto Commands

	" Remove any trailing whitespace that is in the file
"	autocmd BufRead,BufWrite * if ! &bin | silent! %s/\s\+$//ge | endif
"	call histdel("search", -1)

"}}}

" Automatically cd into the directory that the file is in
set autochdir

set ruler
set showcmd
set backspace=indent,eol,start
if &term == "xterm" || &term == "xterm-color"
	set background=light
	#set t_Co=16
	set guifont=fixed
	set hlsearch
	"set visualbell

	" Needed for Syntax Highlighting and stuff
	filetype on
	filetype plugin on
	syntax enable
	set grepprg=grep\ -nH\ $*
	
endif

" Cool tab completion stuff
set wildmenu
set wildmode=list:longest,full

" Enable mouse support in console
set mouse=a

" Who doesn't like autoindent?
set autoindent

" Line Numbers PWN!
set number

" Try this for a bit"
set spell 

" And so is Artificial Intellegence!
set smartcase

"display a warning if fileformat isnt unix
set statusline+=%#warningmsg#
set statusline+=%{&ff!='unix'?'['.&ff.']':''}
set statusline+=%*

"display a warning if file encoding isnt utf-8
set statusline+=%#warningmsg#
set statusline+=%{(&fenc!='utf-8'&&&fenc!='')?'['.&fenc.']':''}
set statusline+=%*

" Automatically handle GPG files
au BufNewFile,BufReadPre *.gpg :set secure vimi= noswap noback nowriteback hist=0 binary
au BufReadPost *.gpg :%!gpg -d 2>/dev/null
au BufWritePre *.gpg :%!gpg -e -r 'name@email.com' 2>/dev/null
au BufWritePost *.gpg u

augroup crontab
    au! BufRead crontab.* set nowritebackup
    au BufRead crontab.* set filetype=crontab
augroup END
