numlockx on
#xscreensaver -no-splash &
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
#setxkbmap -option compose:caps
setxkbmap -option grp:alt_shift_toggle
xhost +localhost &
idesk &
lxpanel &
#launchy &
xbindkeys &
urxvtd -q -f -o &
$(gpg-agent --daemon)
exec openbox-session;
