xscreensaver -no-splash &
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
setxkbmap -option compose:caps
setxkbmap -option grp:alt_shift_toggle
xhost +localhost &
#lxpanel &
#launchy &
xbindkeys &
urxvtd -q -f -o &
#exec openbox-session;
xrandr --output HDMI1 --right-of LVDS1 --primary --auto &
exec i3 -V >> ~/.i3/i3log 2>&1
