#numlockx on &
xscreensaver &
setxkbmap -option compose:caps &
#setxkbmap -option grp:alt_shift_toggle &
xhost +localhost &
idesk &
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
eval $(gpg-agent --daemon) &
exec icewm-session;
