tap "adoptopenjdk/openjdk"
tap "dart-lang/dart"
tap "sass/sass"
brew "python@3.13"
brew "asciinema"
brew "atuin", restart_service: :changed
brew "buf"
brew "colordiff"
brew "coreutils"
brew "exiftool"
brew "ruby"
brew "fastlane"
brew "fdupes"
brew "tesseract"
brew "ffmpeg"
brew "gh"
brew "git"
brew "go"
brew "openjdk"
brew "gradle"
brew "gradle-completion"
brew "graphviz"
brew "imagemagick"
brew "qpdf"
brew "ipython"
brew "jq"
brew "kepubify"
brew "mas"
brew "mtr"
brew "neovim"
brew "ocrmypdf"
brew "openjdk@21"
brew "pandoc"
brew "pre-commit"
brew "python-tk@3.13"
brew "ripgrep"
brew "ruby@3.3"
brew "rustup"
brew "shellcheck"
brew "svgo"
brew "swi-prolog"
brew "transmission-cli"
brew "typos-cli"
brew "vale"
brew "virtualenv"
brew "virtualenvwrapper"
brew "web-ext"
brew "wget"
brew "yt-dlp"
brew "zsh"
brew "sass/sass/sass"
cask "1password-cli"
cask "audacity"
cask "calibre"
cask "gog-galaxy"
cask "gramps"
cask "hex-fiend"
cask "itsycal"
cask "jamovi"
cask "jordanbaird-ice"
cask "keycastr"
cask "kicad"
cask "mactex"
cask "obs"
cask "openscad"
cask "subsurface"
cask "texstudio"
cask "textual"
cask "transmission"
cask "vlc"
cask "wine-stable"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Amphetamine", id: 937984704
mas "Apple Configurator", id: 1037126344
mas "EchoHam", id: 873302145
mas "Essentials", id: 1588151344
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Menu World Time", id: 1446377255
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Remote Desktop", id: 409907375
mas "Tailscale", id: 1475387142
mas "Windows App", id: 1295203466
mas "WireGuard", id: 1451685025
mas "Xcode", id: 497799835
