. ~/.conf/common_shell/rc.sh

source $_shellpath/set-options.zsh
source $_shellpath/alias.zsh
source $_shellpath/complete.zsh
source $_shellpath/keybinding.zsh
source $_shellpath/precmd.zsh

msource ~/.options.post

# Make sure every entry in $fpath is unique.
typeset -U fpath
typeset -U path
