source ~/.conf/common_shell/rc.sh

msource ~/.options.pre

source $_shellpath/start-tmux.sh
source $_shellpath/set-options.zsh
source $_shellpath/zsh.alias.zsh
source $_shellpath/zsh.complete.zsh
source $_shellpath/ps1.zsh
source $_shellpath/keybinding.zsh
source $_shellpath/precmd.zsh

msource ~/.options.post

# Make sure every entry in $fpath is unique.
typeset -U fpath
typeset -U path
